[2025-08-15T01:45:31.329+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-15T01:45:31.403+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: playstore_review_etl_pipeline.transform_clean_reviews scheduled__2025-08-14T00:00:00+00:00 [queued]>
[2025-08-15T01:45:31.419+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: playstore_review_etl_pipeline.transform_clean_reviews scheduled__2025-08-14T00:00:00+00:00 [queued]>
[2025-08-15T01:45:31.421+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 3
[2025-08-15T01:45:31.446+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_clean_reviews> on 2025-08-14 00:00:00+00:00
[2025-08-15T01:45:31.465+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'playstore_review_etl_pipeline', 'transform_clean_reviews', 'scheduled__2025-08-14T00:00:00+00:00', '--job-id', '126', '--raw', '--subdir', 'DAGS_FOLDER/my_pipeline.py', '--cfg-path', '/tmp/tmpe4p6n8cm']
[2025-08-15T01:45:31.472+0000] {standard_task_runner.py:91} INFO - Job 126: Subtask transform_clean_reviews
[2025-08-15T01:45:31.471+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=239) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-08-15T01:45:31.473+0000] {standard_task_runner.py:63} INFO - Started process 241 to run task
[2025-08-15T01:45:31.594+0000] {task_command.py:426} INFO - Running <TaskInstance: playstore_review_etl_pipeline.transform_clean_reviews scheduled__2025-08-14T00:00:00+00:00 [running]> on host 53b91e1bad0a
[2025-08-15T01:45:31.775+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your_email@domain.com' AIRFLOW_CTX_DAG_OWNER='data_engineering_team' AIRFLOW_CTX_DAG_ID='playstore_review_etl_pipeline' AIRFLOW_CTX_TASK_ID='transform_clean_reviews' AIRFLOW_CTX_EXECUTION_DATE='2025-08-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-14T00:00:00+00:00'
[2025-08-15T01:45:31.777+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-15T01:45:31.805+0000] {my_pipeline.py:78} INFO - Starting Processor Task...
[2025-08-15T01:45:31.806+0000] {my_pipeline.py:83} INFO - Calling processor.process_reviews()...
[2025-08-15T01:45:31.807+0000] {processor.py:245} INFO - === Data Processing (NLP Cleaning & VADER Sentiment) Started ===
[2025-08-15T01:45:31.809+0000] {processor.py:111} INFO - Connected to SQLite database at /app/database/reviews.db
[2025-08-15T01:45:31.811+0000] {processor.py:140} INFO - ProcessedAppReviews table checked/created successfully.
[2025-08-15T01:45:31.812+0000] {processor.py:260} INFO - Loading raw reviews from RawAppReviews table...
[2025-08-15T01:45:31.849+0000] {processor.py:263} INFO - Loaded 1980 raw reviews for processing.
[2025-08-15T01:45:31.851+0000] {processor.py:270} INFO - Applying text cleaning and preprocessing...
[2025-08-15T01:45:39.687+0000] {logging_mixin.py:188} WARNING - /opt/***/processor_code/processor.py:163 MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
[2025-08-15T01:45:40.479+0000] {processor.py:272} INFO - Text cleaning and preprocessing completed.
[2025-08-15T01:45:40.480+0000] {processor.py:275} INFO - Calculating review word counts...
[2025-08-15T01:45:40.488+0000] {processor.py:277} INFO - Review word counts calculated.
[2025-08-15T01:45:40.490+0000] {processor.py:280} INFO - Applying VADER sentiment analysis...
[2025-08-15T01:45:40.715+0000] {processor.py:283} INFO - VADER sentiment analysis completed.
[2025-08-15T01:45:40.717+0000] {processor.py:286} INFO - Deriving YearMonth...
[2025-08-15T01:45:40.739+0000] {processor.py:291} INFO - YearMonth derived.
[2025-08-15T01:45:40.741+0000] {processor.py:294} INFO - Preparing data for insertion into ProcessedAppReviews table...
[2025-08-15T01:45:40.753+0000] {processor.py:305} INFO - Converting timestamps for SQLite compatibility...
[2025-08-15T01:45:40.784+0000] {processor.py:314} INFO - Timestamp conversion completed.
[2025-08-15T01:45:40.799+0000] {processor.py:318} INFO - Prepared 1980 records for insertion.
[2025-08-15T01:45:40.801+0000] {processor.py:329} INFO - Inserting processed data into ProcessedAppReviews table...
[2025-08-15T01:45:40.802+0000] {processor.py:336} ERROR - SQLite error during data insertion: Error binding parameter 5: type 'Timestamp' is not supported
[2025-08-15T01:45:40.803+0000] {processor.py:349} ERROR - === Data Processing Failed! Error: Error binding parameter 5: type 'Timestamp' is not supported ===
Traceback (most recent call last):
  File "/opt/airflow/processor_code/processor.py", line 331, in process_reviews
    cursor.executemany(insert_query, records)
sqlite3.ProgrammingError: Error binding parameter 5: type 'Timestamp' is not supported
[2025-08-15T01:45:40.813+0000] {processor.py:356} INFO - Database connection closed.
[2025-08-15T01:45:40.814+0000] {my_pipeline.py:95} ERROR - Processor task failed with exception: Error binding parameter 5: type 'Timestamp' is not supported
Traceback (most recent call last):
  File "/opt/airflow/dags/my_pipeline.py", line 84, in run_processor
    processor_module.process_reviews() # Execute the processing logic
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/processor_code/processor.py", line 331, in process_reviews
    cursor.executemany(insert_query, records)
sqlite3.ProgrammingError: Error binding parameter 5: type 'Timestamp' is not supported
[2025-08-15T01:45:40.823+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-15T01:45:40.825+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/my_pipeline.py", line 84, in run_processor
    processor_module.process_reviews() # Execute the processing logic
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/processor_code/processor.py", line 331, in process_reviews
    cursor.executemany(insert_query, records)
sqlite3.ProgrammingError: Error binding parameter 5: type 'Timestamp' is not supported
[2025-08-15T01:45:40.850+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=playstore_review_etl_pipeline, task_id=transform_clean_reviews, run_id=scheduled__2025-08-14T00:00:00+00:00, execution_date=20250814T000000, start_date=20250815T014531, end_date=20250815T014540
[2025-08-15T01:45:40.877+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 126 for task transform_clean_reviews (Error binding parameter 5: type 'Timestamp' is not supported; 241)
[2025-08-15T01:45:40.936+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-15T01:45:40.988+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-15T01:45:41.001+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
