[2025-08-15T01:41:06.492+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-15T01:41:06.628+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: playstore_review_etl_pipeline.transform_clean_reviews scheduled__2025-08-14T00:00:00+00:00 [queued]>
[2025-08-15T01:41:06.650+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: playstore_review_etl_pipeline.transform_clean_reviews scheduled__2025-08-14T00:00:00+00:00 [queued]>
[2025-08-15T01:41:06.653+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-08-15T01:41:06.695+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_clean_reviews> on 2025-08-14 00:00:00+00:00
[2025-08-15T01:41:06.722+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'playstore_review_etl_pipeline', 'transform_clean_reviews', 'scheduled__2025-08-14T00:00:00+00:00', '--job-id', '124', '--raw', '--subdir', 'DAGS_FOLDER/my_pipeline.py', '--cfg-path', '/tmp/tmpj394acay']
[2025-08-15T01:41:06.735+0000] {standard_task_runner.py:91} INFO - Job 124: Subtask transform_clean_reviews
[2025-08-15T01:41:06.737+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=185) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-08-15T01:41:06.739+0000] {standard_task_runner.py:63} INFO - Started process 187 to run task
[2025-08-15T01:41:06.857+0000] {task_command.py:426} INFO - Running <TaskInstance: playstore_review_etl_pipeline.transform_clean_reviews scheduled__2025-08-14T00:00:00+00:00 [running]> on host 53b91e1bad0a
[2025-08-15T01:41:07.103+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your_email@domain.com' AIRFLOW_CTX_DAG_OWNER='data_engineering_team' AIRFLOW_CTX_DAG_ID='playstore_review_etl_pipeline' AIRFLOW_CTX_TASK_ID='transform_clean_reviews' AIRFLOW_CTX_EXECUTION_DATE='2025-08-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-14T00:00:00+00:00'
[2025-08-15T01:41:07.108+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-15T01:41:07.143+0000] {my_pipeline.py:78} INFO - Starting Processor Task...
[2025-08-15T01:41:07.144+0000] {my_pipeline.py:83} INFO - Calling processor.process_reviews()...
[2025-08-15T01:41:07.145+0000] {processor.py:245} INFO - === Data Processing (NLP Cleaning & VADER Sentiment) Started ===
[2025-08-15T01:41:07.147+0000] {processor.py:111} INFO - Connected to SQLite database at /app/database/reviews.db
[2025-08-15T01:41:07.151+0000] {processor.py:140} INFO - ProcessedAppReviews table checked/created successfully.
[2025-08-15T01:41:07.152+0000] {processor.py:260} INFO - Loading raw reviews from RawAppReviews table...
[2025-08-15T01:41:07.216+0000] {processor.py:263} INFO - Loaded 1980 raw reviews for processing.
[2025-08-15T01:41:07.218+0000] {processor.py:270} INFO - Applying text cleaning and preprocessing...
[2025-08-15T01:41:16.260+0000] {logging_mixin.py:188} WARNING - /opt/***/processor_code/processor.py:163 MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
[2025-08-15T01:41:16.835+0000] {processor.py:272} INFO - Text cleaning and preprocessing completed.
[2025-08-15T01:41:16.837+0000] {processor.py:275} INFO - Calculating review word counts...
[2025-08-15T01:41:16.845+0000] {processor.py:277} INFO - Review word counts calculated.
[2025-08-15T01:41:16.846+0000] {processor.py:280} INFO - Applying VADER sentiment analysis...
[2025-08-15T01:41:17.051+0000] {processor.py:283} INFO - VADER sentiment analysis completed.
[2025-08-15T01:41:17.055+0000] {processor.py:286} INFO - Deriving YearMonth...
[2025-08-15T01:41:17.085+0000] {processor.py:291} INFO - YearMonth derived.
[2025-08-15T01:41:17.087+0000] {processor.py:294} INFO - Preparing data for insertion into ProcessedAppReviews table...
[2025-08-15T01:41:17.101+0000] {processor.py:305} INFO - Converting timestamps for SQLite compatibility...
[2025-08-15T01:41:17.144+0000] {processor.py:314} INFO - Timestamp conversion completed.
[2025-08-15T01:41:17.168+0000] {processor.py:318} INFO - Prepared 1980 records for insertion.
[2025-08-15T01:41:17.171+0000] {processor.py:329} INFO - Inserting processed data into ProcessedAppReviews table...
[2025-08-15T01:41:17.173+0000] {processor.py:336} ERROR - SQLite error during data insertion: Error binding parameter 5: type 'Timestamp' is not supported
[2025-08-15T01:41:17.175+0000] {processor.py:349} ERROR - === Data Processing Failed! Error: Error binding parameter 5: type 'Timestamp' is not supported ===
Traceback (most recent call last):
  File "/opt/airflow/processor_code/processor.py", line 331, in process_reviews
    cursor.executemany(insert_query, records)
sqlite3.ProgrammingError: Error binding parameter 5: type 'Timestamp' is not supported
[2025-08-15T01:41:17.188+0000] {processor.py:356} INFO - Database connection closed.
[2025-08-15T01:41:17.190+0000] {my_pipeline.py:95} ERROR - Processor task failed with exception: Error binding parameter 5: type 'Timestamp' is not supported
Traceback (most recent call last):
  File "/opt/airflow/dags/my_pipeline.py", line 84, in run_processor
    processor_module.process_reviews() # Execute the processing logic
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/processor_code/processor.py", line 331, in process_reviews
    cursor.executemany(insert_query, records)
sqlite3.ProgrammingError: Error binding parameter 5: type 'Timestamp' is not supported
[2025-08-15T01:41:17.201+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-15T01:41:17.204+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/my_pipeline.py", line 84, in run_processor
    processor_module.process_reviews() # Execute the processing logic
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/processor_code/processor.py", line 331, in process_reviews
    cursor.executemany(insert_query, records)
sqlite3.ProgrammingError: Error binding parameter 5: type 'Timestamp' is not supported
[2025-08-15T01:41:17.229+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=playstore_review_etl_pipeline, task_id=transform_clean_reviews, run_id=scheduled__2025-08-14T00:00:00+00:00, execution_date=20250814T000000, start_date=20250815T014106, end_date=20250815T014117
[2025-08-15T01:41:17.258+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 124 for task transform_clean_reviews (Error binding parameter 5: type 'Timestamp' is not supported; 187)
[2025-08-15T01:41:17.328+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-15T01:41:17.379+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-15T01:41:17.383+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
