[2025-08-14T03:46:31.950+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-14T03:46:32.052+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: playstore_review_etl_pipeline.transform_clean_reviews manual__2025-08-14T03:41:16.307492+00:00 [queued]>
[2025-08-14T03:46:32.080+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: playstore_review_etl_pipeline.transform_clean_reviews manual__2025-08-14T03:41:16.307492+00:00 [queued]>
[2025-08-14T03:46:32.083+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 3
[2025-08-14T03:46:32.119+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_clean_reviews> on 2025-08-14 03:41:16.307492+00:00
[2025-08-14T03:46:32.153+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'playstore_review_etl_pipeline', 'transform_clean_reviews', 'manual__2025-08-14T03:41:16.307492+00:00', '--job-id', '120', '--raw', '--subdir', 'DAGS_FOLDER/my_pipeline.py', '--cfg-path', '/tmp/tmp_1c35x38']
[2025-08-14T03:46:32.173+0000] {standard_task_runner.py:91} INFO - Job 120: Subtask transform_clean_reviews
[2025-08-14T03:46:32.174+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=251) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-08-14T03:46:32.187+0000] {standard_task_runner.py:63} INFO - Started process 253 to run task
[2025-08-14T03:46:32.331+0000] {task_command.py:426} INFO - Running <TaskInstance: playstore_review_etl_pipeline.transform_clean_reviews manual__2025-08-14T03:41:16.307492+00:00 [running]> on host 53b91e1bad0a
[2025-08-14T03:46:32.615+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your_email@domain.com' AIRFLOW_CTX_DAG_OWNER='data_engineering_team' AIRFLOW_CTX_DAG_ID='playstore_review_etl_pipeline' AIRFLOW_CTX_TASK_ID='transform_clean_reviews' AIRFLOW_CTX_EXECUTION_DATE='2025-08-14T03:41:16.307492+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-14T03:41:16.307492+00:00'
[2025-08-14T03:46:32.621+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-14T03:46:32.679+0000] {my_pipeline.py:78} INFO - Starting Processor Task...
[2025-08-14T03:46:32.684+0000] {my_pipeline.py:83} INFO - Calling processor.process_reviews()...
[2025-08-14T03:46:32.687+0000] {processor.py:245} INFO - === Data Processing (NLP Cleaning & VADER Sentiment) Started ===
[2025-08-14T03:46:32.690+0000] {processor.py:111} INFO - Connected to SQLite database at /app/database/reviews.db
[2025-08-14T03:46:32.700+0000] {processor.py:140} INFO - ProcessedAppReviews table checked/created successfully.
[2025-08-14T03:46:32.701+0000] {processor.py:260} INFO - Loading raw reviews from RawAppReviews table...
[2025-08-14T03:46:32.783+0000] {processor.py:263} INFO - Loaded 1753 raw reviews for processing.
[2025-08-14T03:46:32.785+0000] {processor.py:270} INFO - Applying text cleaning and preprocessing...
[2025-08-14T03:46:40.943+0000] {logging_mixin.py:188} WARNING - /opt/***/processor_code/processor.py:163 MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
[2025-08-14T03:46:41.422+0000] {processor.py:272} INFO - Text cleaning and preprocessing completed.
[2025-08-14T03:46:41.423+0000] {processor.py:275} INFO - Calculating review word counts...
[2025-08-14T03:46:41.427+0000] {processor.py:277} INFO - Review word counts calculated.
[2025-08-14T03:46:41.428+0000] {processor.py:280} INFO - Applying VADER sentiment analysis...
[2025-08-14T03:46:41.534+0000] {processor.py:283} INFO - VADER sentiment analysis completed.
[2025-08-14T03:46:41.535+0000] {processor.py:286} INFO - Deriving YearMonth...
[2025-08-14T03:46:41.549+0000] {processor.py:291} INFO - YearMonth derived.
[2025-08-14T03:46:41.550+0000] {processor.py:294} INFO - Preparing data for insertion into ProcessedAppReviews table...
[2025-08-14T03:46:41.556+0000] {processor.py:305} INFO - Converting timestamps for SQLite compatibility...
[2025-08-14T03:46:41.576+0000] {processor.py:314} INFO - Timestamp conversion completed.
[2025-08-14T03:46:41.586+0000] {processor.py:318} INFO - Prepared 1753 records for insertion.
[2025-08-14T03:46:41.587+0000] {processor.py:329} INFO - Inserting processed data into ProcessedAppReviews table...
[2025-08-14T03:46:41.589+0000] {processor.py:336} ERROR - SQLite error during data insertion: Error binding parameter 5: type 'Timestamp' is not supported
[2025-08-14T03:46:41.590+0000] {processor.py:349} ERROR - === Data Processing Failed! Error: Error binding parameter 5: type 'Timestamp' is not supported ===
Traceback (most recent call last):
  File "/opt/airflow/processor_code/processor.py", line 331, in process_reviews
    cursor.executemany(insert_query, records)
sqlite3.ProgrammingError: Error binding parameter 5: type 'Timestamp' is not supported
[2025-08-14T03:46:41.600+0000] {processor.py:356} INFO - Database connection closed.
[2025-08-14T03:46:41.602+0000] {my_pipeline.py:95} ERROR - Processor task failed with exception: Error binding parameter 5: type 'Timestamp' is not supported
Traceback (most recent call last):
  File "/opt/airflow/dags/my_pipeline.py", line 84, in run_processor
    processor_module.process_reviews() # Execute the processing logic
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/processor_code/processor.py", line 331, in process_reviews
    cursor.executemany(insert_query, records)
sqlite3.ProgrammingError: Error binding parameter 5: type 'Timestamp' is not supported
[2025-08-14T03:46:41.612+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-14T03:46:41.614+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/my_pipeline.py", line 84, in run_processor
    processor_module.process_reviews() # Execute the processing logic
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/processor_code/processor.py", line 331, in process_reviews
    cursor.executemany(insert_query, records)
sqlite3.ProgrammingError: Error binding parameter 5: type 'Timestamp' is not supported
[2025-08-14T03:46:41.637+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=playstore_review_etl_pipeline, task_id=transform_clean_reviews, run_id=manual__2025-08-14T03:41:16.307492+00:00, execution_date=20250814T034116, start_date=20250814T034632, end_date=20250814T034641
[2025-08-14T03:46:41.665+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 120 for task transform_clean_reviews (Error binding parameter 5: type 'Timestamp' is not supported; 253)
[2025-08-14T03:46:41.730+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-14T03:46:41.797+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-14T03:46:41.809+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
