[2025-08-15T01:40:59.800+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-15T01:40:59.966+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: playstore_review_etl_pipeline.validate_raw_reviews scheduled__2025-08-14T00:00:00+00:00 [queued]>
[2025-08-15T01:40:59.997+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: playstore_review_etl_pipeline.validate_raw_reviews scheduled__2025-08-14T00:00:00+00:00 [queued]>
[2025-08-15T01:40:59.998+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-08-15T01:41:00.105+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): validate_raw_reviews> on 2025-08-14 00:00:00+00:00
[2025-08-15T01:41:00.203+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=182) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-08-15T01:41:00.223+0000] {standard_task_runner.py:63} INFO - Started process 184 to run task
[2025-08-15T01:41:00.215+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'playstore_review_etl_pipeline', 'validate_raw_reviews', 'scheduled__2025-08-14T00:00:00+00:00', '--job-id', '123', '--raw', '--subdir', 'DAGS_FOLDER/my_pipeline.py', '--cfg-path', '/tmp/tmp9o4mjp0c']
[2025-08-15T01:41:00.242+0000] {standard_task_runner.py:91} INFO - Job 123: Subtask validate_raw_reviews
[2025-08-15T01:41:00.525+0000] {task_command.py:426} INFO - Running <TaskInstance: playstore_review_etl_pipeline.validate_raw_reviews scheduled__2025-08-14T00:00:00+00:00 [running]> on host 53b91e1bad0a
[2025-08-15T01:41:00.846+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your_email@domain.com' AIRFLOW_CTX_DAG_OWNER='data_engineering_team' AIRFLOW_CTX_DAG_ID='playstore_review_etl_pipeline' AIRFLOW_CTX_TASK_ID='validate_raw_reviews' AIRFLOW_CTX_EXECUTION_DATE='2025-08-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-14T00:00:00+00:00'
[2025-08-15T01:41:00.849+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-15T01:41:00.899+0000] {my_pipeline.py:107} INFO - Running validation on RawAppReviews data (Placeholder).
[2025-08-15T01:41:00.900+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-08-15T01:41:00.902+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-15T01:41:00.928+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=playstore_review_etl_pipeline, task_id=validate_raw_reviews, run_id=scheduled__2025-08-14T00:00:00+00:00, execution_date=20250814T000000, start_date=20250815T014059, end_date=20250815T014100
[2025-08-15T01:41:00.973+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-08-15T01:41:01.054+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-08-15T01:41:01.062+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
